export type DashboardSection =
  | 'decisions'
  | 'drift-by-product-area'
  | 'drift-by-team'
  | 'drift-events'
  | 'drift-graph'
  | 'drift-report'
  | 'drift-timeline'
  | 'evidence'
  | 'evolution'
  | 'intentional-drift'
  | 'overview'
  | 'people'
  | 'reports'
  | 'settings'
  | 'unexplained-drift'
  | 'vision-baseline'
